### ISSUE TITLE
Markdown rendering bug

### ISSUE THREAD

**Issue by MichielDeMey** [assemble/grunt-assemble#25]
Hey guys, I'd like to report a strange issue with markdown rendering.
This is most likely a bug in the markdown renderer that you use, however I could not find which one.

The following bug is observed:
```markdown
---
title: Foo
---

# This is rendered as a header

<section>

  # This is not rendered as a header

</section>
```

output:

```html
<h1>This is rendered as a header</h1>

<section>

  # This is not rendered as a header

</section>
```

The first header is rendered in html as an `h1`, however the second header inside the section tags is ignored and outputted literally.

I'm including the content as suggested in the documentation:

```handlebars
{{#markdown }}
  {{> body  }}
{{/markdown }}
```

Using `grunt-assemble 0.4.0`

Technically, this should work, right? Any ideas?

**Comment by MichielDeMey** [comment]
Apparently it's a known issue with Marked.
https://github.com/chjj/marked/issues/488

**Comment by bchavezgd** [comment]
that's an issue with markdown itself. you can't put html inside markdown inside html, it won't render. 

(see original reason)[https://daringfireball.net/projects/markdown/syntax#html]

**Comment by jonschlinkert** [comment]
> you can't put html inside markdown inside html, it won't render.

yeah that's correct. Also, I think the markdown helpers in grunt-assemble use marked (from the handlebars-helpers lib), which does not follow commonmark spec.  

Also fwiw in the 0.6. branch of handlebars-helpers, the markdown helpers were updated to use [remarkable](https://github.com/jonschlinkert/remarkable), a much better markdown parser that follows commonmark. 

closing since this isn't really an issue, but feel free to continue the conversation
